"""empty message

Revision ID: 14801fac2594
Revises: f41983aebdc5
Create Date: 2023-04-04 20:50:41.130940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14801fac2594'
down_revision = 'f41983aebdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_show')
    with op.batch_alter_table('user_hist_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_hist_rating', schema=None) as batch_op:
        batch_op.drop_column('venue_id')

    op.create_table('_alembic_tmp_show',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ticket_price', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('show_timing', sa.DATETIME(), nullable=True),
    sa.Column('available_seats', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
