"""AdminLogin

Revision ID: 36ef0ab34ec1
Revises: 
Create Date: 2023-03-17 12:27:14.262742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ef0ab34ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.drop_table('Admin')
    # ### end Alembic commands ###
