"""date time added to show

Revision ID: 808421fba6fd
Revises: 
Create Date: 2023-03-25 19:05:11.201984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808421fba6fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_timing', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('show_timing')

    # ### end Alembic commands ###
