"""constraints add p2

Revision ID: cb99f1ea4951
Revises: aff61779accb
Create Date: 2023-04-23 19:19:40.723403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb99f1ea4951'
down_revision = 'aff61779accb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user_hist_rating', schema=None) as batch_op:
        batch_op.alter_column('user_rating',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_hist_rating', schema=None) as batch_op:
        batch_op.alter_column('user_rating',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
